defaults:
  - hydra: default
  - env: default
  - log: default

worker: eval_linear_probe
output_dir: checkpoints/eval
job_name: eval_linear_probe_pastis_hr_model_run1_classignorefix_tiles4_median_tempfeatpooling
pretrain_job_name:

# Dataset
dataset: pastis
data_path: /home/admin/AGML_ResearchGroup/SuperResolution/pastis
img_size: 224
num_classes: 18
tiles_per_img: 4  # Split each 128x128 into 4 64x64 tiles (or 1 for full image)

# Model
encoder: vit_small
use_batchnorm: False

# Evaluation mode
eval_mode: linear_probe  # or 'finetune'

# Checkpoint
pretrained_checkpoint: /home/admin/john/LatentMIM/checkpoints/hr_model/checkpoint_0300.pth
resume: False
checkpoint_metric: miou  # 'miou' or 'loss'

# Training
epochs: 100
warmup_epochs: 10
batch_size: 64
accum_iter: 1

# Optimizer
blr:
lr: 1e-3
min_lr_frac: 1
weight_decay: 0.0

env:
  workers: 8
